### ISSUE TITLE
Change default port number?

### ISSUE THREAD

**Issue by oparada1988** [muesli/obs-cli#58] opened 2022-05-24 15:54 UTC
Hello, 

Question, is there a way to change the default port number? I understand we can use the --port flag but was curious to see if there is a way to just change it

**Comment by muesli** [comment] 2022-05-24 16:09
Yes, `--port` is the answer to this question. Are you looking for a config file? That doesn't exist, at least for now.

**Comment by oparada1988** [comment] 2022-05-24 16:11
> Yes, `--port` is the answer to this question. Are you looking for a config file? That doesn't exist, at least for now.

Yeah I was looking for a config file. Hopefully it gets added later on 🙂

**Comment by muesli** [comment] 2022-05-24 21:58
Thanks, closing this as a dupe of #28 then.

**Closed by muesli** 2022-05-24 21:58 UTC
Labels: duplicate
